name: openapi-extract and diff with develop

# GitHub Pages ì„¤ì • í•„ìš”:
# Repository Settings -> Pages -> Source: Deploy from a branch -> gh-pages branch

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main # main ë¸Œëœì¹˜

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate OpenAPI spec for main
        run: ./gradlew clean generateOpenApiDocs

      - uses: actions/upload-artifact@v4 # ì•„í‹°íŒ©íŠ¸ ì—…ë¡œë“œ
        with:
          name: main-spec
          path: build/openapi.json

      - name: Swagger UI Action
        uses: Legion2/swagger-ui-action@v1.3.0
        with:
          output: swagger-ui
          spec-file: build/openapi.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  #gh-pages ë¸Œëœì¹˜ rootì— swagger-ui push
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui

  build-develop:
    runs-on: ubuntu-latest
    needs: build-main
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop  # develop ë¸Œëœì¹˜ì™€ ë¹„êµ

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate OpenAPI spec for develop
        run: ./gradlew clean generateOpenApiDocs

      - uses: actions/download-artifact@v4 # ì•„í‹°íŒ©íŠ¸ ë‹¤ìš´ë¡œë“œ
        with:
          name: main-spec
          path: ./main

      - name: List downloaded main artifact files # ê²½ë¡œ í™•ì¸
        run: ls -R ./main

      - name: Run openapi-diff with docker # ë„ì»¤ í—ˆë¸Œì—ì„œ ì´ë¯¸ì§€ ì‚¬ìš©
        run: docker run --rm -v ${{ github.workspace }}:/specs openapitools/openapi-diff:latest /specs/main/openapi.json /specs/build/openapi.json --json /specs/diff.json

      - name: Show diff result
        run: |
          echo "ğŸ“Š API Diff Result (main vs develop):"
          cat diff.json
